package helper

func GetMessage(message string) string {
	messages := map[string]string{
		"TRANSACTION_CONFIRMED":             "Транзакция подтверждена",
		"GOLD_COINS_HAVE_BEEN_SOLD":         "Золотые монеты были успешно проданы",
		"REAL_ESTATE_HAS_BEEN_SOLD":         "Недвижимость была успешно продана",
		"GOLD_HAVE_BEEN_SOLD":               "Золото было успешно продано",
		"FAIL_LOST_MLM":                     "Ваша МЛМ структура обрушилась...",
		"PAYDAY_MESSAGE":                    "Сегодня день зарплаты, поздравляем!",
		"CASHFLOW_DAY_MESSAGE":              "Сегодня день получения дивидендов от пассивного дохода, поздравляем!",
		"GOT_CASH_BY_MLM":                   "Вы получили дивиденды от своей МЛМ структуры в размере: $%w",
		"SHARES_HAVE_BEEN_SOLD":             "Акции были успешно проданы",
		"YOU_HAVE_PAID_PROPERTY_DAMAGE":     "Вы заплатили за повреждённую собственность",
		"YOU_HAVE_PAID_DOODAD":              "Поздравляем Вас с покупкой...",
		"SPLIT_STOCKS":                      "Акции компании %w были удвоенны",
		"REVERSE_SPLIT_STOCKS":              "Часть акций компании %w были сожжены",
		"YOU_PARTICIPATED_LOTTERY":          "Вы поучавствовали в лотерее",
		"YOU_PARTICIPATED_LOTTERY_AND_LOST": "Вы поучавствовали в лотерее и к сожалению проиграли...",
		"YOU_PARTICIPATED_LOTTERY_AND_WON":  "Вы успешно поучавствовали в лотерее и выграли $%w",
		"YOU_BOUGHT_REAL_ESTATE":            "Вы успешно приобрели недвижимость",
		"YOU_BOUGHT_STOCKS":                 "Вы успешно приобрели акции данной компании",
		"YOU_BOUGHT_GOLD_COINS":             "Вы успешно приобрели золотые монеты",
		"YOU_PARTICIPATED_MLM":              "Вы теперь участник МЛМ структуры",
		"YOU_PARTICIPATED_CHARITY":          "Вы успешно поучавствовали в благотворительности",
		"YOU_PARTICIPATED_BIG_CHARITY":      "Вы успешно поучавствовали в Акции Милосердия",
		"YOU_WAS_DOWNSIZED":                 "К сожалению Вас уволили...",
		"RISK_REQUEST_DECLINED":             "К сожалению риск не оправдал надежды",
		"HAVE_NO_DEFINED_CARD":              "Карточка не доступна",
		"YOU_HAVE_NO_BABIES":                "У Вас нету детей",
		"YOU_HAVE_CHILD_BOY":                "Поздравляем, у Вас родился мальчик!",
		"YOU_HAVE_CHILD_GIRL":               "Поздравляем, у Вас родилась девочка!",
		"GOT_TAX_50_PERCENT":                "С Вас взымается плата в размере 50% своих средств",
		"GOT_TAX_100_PERCENT":               "С Вас взымается плата в размере 100% своих средств",
		"YOU_BECOME_BANKRUPT":               "Вы банкрот... Начните жизнь с чистого листа, но с приобретённым опытом!",
		"FAIL_RISK_DEAL":                    "Вы к сожалению рискованный бизнес обошёл Вас стороной...",
		"SUCCESS_RISK_DEAL":                 "Вы приобрели рискованный бизнес!",
		"SUCCESS_RISK_STOCKS_DEAL":          "Вы успешно приобрели акции рискованного бизнеса!",
		"FAIL_RISK_STOCKS_DEAL":             "Вы потеряли деньги на бесполезных акциях...",
		"YOU_BOUGHT_DREAM":                  "Вы успешно приобрели мечту!",
		"YOU_BOUGHT_PERSONAL_DREAM":         "Вы успешно приобрели СВОЮ мечту! Поздравляем!",
		"YOU_BOUGHT_BUSINESS":               "Вы успешно приобрели бизнес!",
		"ERROR_NOT_FOUND_ASSET":             "Нет такого актива",
		"ERROR_NOT_ENOUGH_MONEY":            "Не хватает денег на балансе",
		"ERROR_NOT_FOUND_STOCKS":            "Акции не найдены в инвестиционном портфеле",
		"ERROR_NOT_ENOUGH_STOCKS":           "Акции в таком количестве не найдены в инвестиционном портфеле",
		"ERROR_NOT_ENOUGH_ASSET":            "Нет такой позиции в инвест. портфеле",
		"ERROR_YOU_HAVE_NO_PROPERTIES":      "У вас нет недвижимости",
		"ERROR_TRANSACTION_DECLINED":        "Транзакция отклонена",
		"ERROR_INSUFFICIENT_PLAYERS":        "Недостающее кол-во игроков (2 или более).",
		"ERROR_MOVING_BIG_RACE_DECLINED":    "Переход на большой круг отклонён",
		"ERROR_CANNOT_TAKE_BIG_DEALS":       "Для больших сделок Вам нужно минимум $10000 наличных средств",
	}

	return messages[message]
}
