version: '3'
services:
  golang:
    build: .
    ports:
      - "8080:8080"
    restart: always

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: E|#,78b@8F@=6}8RcZ!G
      MYSQL_DATABASE: cashcome_db
    restart: always