# Use the official Golang image as a parent image.
FROM golang:1.18

# Set the working directory.
WORKDIR /app

# Copy the Go module files.
COPY go.mod go.sum ./

# Download dependencies.
RUN go mod download

# Copy the rest of the application.
COPY . .

RUN chmod +x ./cmd/entrypoint.sh

# Set the entrypoint script to be executed.
ENTRYPOINT ["./cmd/entrypoint.sh"]

WORKDIR /app

# Command to run the application.
CMD ["go", "run", "."]