version: '3'
services:
  golang:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - PORT=${PORT}

      - CARDS_PATH=${CARDS_PATH}
      - PROFESSIONS_PATH=${PROFESSIONS_PATH}

      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}

      - SECRET=${SECRET}
      - ENV=${ENV}
      - REDIS_URL=${REDIS_URL}

      - JWT_SECRET=${JWT_SECRET}
    networks:
      - cashcome  # Uses the shared network
    ports:
      - "8080:8080"
    restart: on-failure

  mysql:
    platform: "linux/x86_64"
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ../mysql-data:/var/lib/mysql
    networks:
      cashcome:
        aliases:
          - mysql-db  # Alternative alias for the MySQL service

networks:
  cashcome:
    external:
      name: cashcome