apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: cashflow-backend
build:
  artifacts:
    - image: cashflow-backend
      context: .
      hooks:
        before:
          - command: [ "bash", "./cmd/check_conditions.sh" ]
            os: [ linux, darwin, windows ]
      docker:
        dockerfile: Dockerfile.prod.dev
deploy:
  kubectl:
    manifests:
      - ./k8s/*.yaml