package storage

const (
	ErrorUndefinedUser            = "error undefined user"
	ErrorUndefinedPlayer          = "error undefined player"
	ErrorUndefinedReceiverPlayer  = "error undefined receiver player"
	ErrorUndefinedGame            = "error undefined game"
	ErrorGameIsFull               = "error game is full"
	ErrorGameIsStarted            = "error game is started"
	ErrorUndefinedLobby           = "error undefined lobby"
	ErrorCannotCreatedRace        = "error cannot created race"
	ErrorCannotTakeBigDeals       = "error cannot take big deals"
	ErrorForbidden                = "error forbidden"
	ErrorProcessFailed            = "error process failed"
	ErrorIsNotValidCountValue     = "error is not valid count value"
	ErrorIsNotValidRealEstate     = "error is not valid real estate"
	ErrorInvalidTypeOfCard        = "error invalid type of card"
	ErrorUndefinedDiceValue       = "error undefined dice value"
	ErrorYouHaveNoBabies          = "error you have no babies"
	ErrorNotFoundAssets           = "error not found assets"
	ErrorNotEnoughMoney           = "error not enough money"
	ErrorNotFoundStocks           = "error not found stocks"
	ErrorNotEnoughStocks          = "error not enough stocks"
	ErrorUndefinedProfession      = "error undefined profession"
	ErrorYouHaveTooManyBabies     = "error you have too many babies"
	ErrorNotEnoughAsset           = "error not enough asset"
	ErrorPermissionDenied         = "error permission denied"
	ErrorWrongAmountForTakingLoan = "error wrong amount for taking loan"
	ErrorYouHaveNoProperties      = "error you have no properties"
	ErrorTransactionDeclined      = "error transaction declined"
	ErrorInsufficientPlayers      = "error insufficient players"
	ErrorMovingBigRaceDeclined    = "error moving big race declined"
)
