package storage

const (
	ErrorUndefinedUser                                = "error undefined user"
	ErrorUndefinedPlayer                              = "error undefined player"
	ErrorUndefinedReceiverPlayer                      = "error undefined receiver player"
	ErrorUndefinedGame                                = "error undefined game"
	ErrorGameIsFull                                   = "error game is full"
	ErrorGameIsStarted                                = "error game is started"
	ErrorUndefinedLobby                               = "error undefined lobby"
	ErrorCannotCreatedRace                            = "error cannot created race"
	ErrorCannotTakeBigDeals                           = "error cannot take big deals"
	ErrorForbidden                                    = "error forbidden"
	ErrorProcessFailed                                = "error process failed"
	ErrorIsNotValidCountValue                         = "error is not valid count value"
	ErrorIsNotValidRealEstate                         = "error is not valid real estate"
	ErrorIsNotValidBusiness                           = "error is not valid business"
	ErrorIsNotValidOtherAssets                        = "error is not valid other assets"
	ErrorInvalidTypeOfCard                            = "error invalid type of card"
	ErrorWrongAmount                                  = "error wrong amount"
	ErrorYouHaveNoBabies                              = "error you have no babies"
	ErrorTooManyAssets                                = "error too many assets"
	ErrorNotFoundAssets                               = "error not found assets"
	ErrorNotEnoughMoney                               = "error not enough money"
	ErrorNotFoundStocks                               = "error not found stocks"
	ErrorNotEnoughStocks                              = "error not enough stocks"
	ErrorUndefinedProfession                          = "error undefined profession"
	ErrorInvalidCard                                  = "error invalid card"
	ErrorNotEnoughAsset                               = "error not enough asset"
	ErrorPermissionDenied                             = "error permission denied"
	ErrorWrongAmountForTakingLoan                     = "error wrong amount for taking loan"
	ErrorWrongAmountForPayingLoan                     = "error wrong amount for paying loan"
	ErrorCommonPassiveIncomeGreaterThanCashFlowOfCard = "error common passive income greater than cash flow of the card"
	ErrorYouHaveNoProperties                          = "error you have no properties"
	ErrorNotSuitableBuilding                          = "error not suitable building"
	ErrorLimitedPartnership                           = "error limited partnership"
	ErrorIncorrectCount                               = "error incorrect count"
	ErrorUndefinedTypeOfDeal                          = "error undefined type of deal"
	ErrorInsufficientPlayers                          = "error insufficient players"
	ErrorMovingBigRaceDeclined                        = "error moving big race declined"
	ErrorYouAreBankrupt                               = "error you are bankrupt"
	ErrorForbiddenByOwner                             = "error forbidden by owner"
)
